export enum ToolCapability {
  READ_FILE = 'READ_FILE',
  WRITE_FILE = 'WRITE_FILE',
  NETWORK_REQUEST = 'NETWORK_REQUEST',
  STATE_MUTATION = 'STATE_MUTATION',
  BROWSER_CONTROL = 'BROWSER_CONTROL',
  CODE_EXECUTION = 'CODE_EXECUTION',
  API_INTERACTION = 'API_INTERACTION',
  DATA_PROCESSING = 'DATA_PROCESSING',
  SYSTEM_COMMAND = 'SYSTEM_COMMAND',
  UNKNOWN = 'UNKNOWN'
}
