export enum ToolProviderCapability {
  HEALTH_CHECK = 'HEALTH_CHECK',
  DYNAMIC_DISCOVERY = 'DYNAMIC_DISCOVERY',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  STREAMING_SUPPORT = 'STREAMING_SUPPORT',
  CANCELLATION_SUPPORT = 'CANCELLATION_SUPPORT',
  TIMEOUT_SUPPORT = 'TIMEOUT_SUPPORT'
}
